=== chhartmann/RoboProg/data/config-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "limits": {
        "type": "array",
        "description": "Limits of the joints",
        "items": [
          {
            "type": "object",
            "properties": {
              "min": {
                "type": "integer",
                "minimum": -180,
                "maximum": 180
              },
              "max": {
                "type": "integer",
                "minimum": -180,
                "maximum": 180
              }
            },
            "required": [
              "min",
              "max"
            ]
          }
        ]
      },
      "home": {
        "type": "array",
        "description": "Home position of the joints",
        "items": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 180
          }
        ]
      },
      "offset": {
        "type": "array",
        "description": "Zero position of the joints relative to the servo position",
        "items": [
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 180
          }
        ]
      },
      "direction": {
        "type": "array",
        "description": "Direction of the joints",
        "items": [
          {
            "type": "integer",
            "enum": [-1, 1]
          }
        ]
      },
      "Autostart-Script": {
        "type": "boolean",
        "description": "Run script at startup"
      },
      "Wifi-SSID": {
        "type": "string",
        "maxLength" : 31,
        "description": "WiFi SSID"
      },
      "Wifi-Password": {
        "type": "string",
        "maxLength" : 63,
        "description": "WiFi Password"
      },
      "Hostname": {
        "type": "string",
        "description": "Hostname of the RobotProg controller"
      },
      "ROS-Agent-IP": {
        "type": "string",
        "description": "IP of the ROS Agent",
        "pattern" : "(([0-9]{1,3}\\.){3}[0-9]{1,3})|(^$)"
      }
    },
    "required": [
      "limits",
      "Wifi-SSID",
      "Wifi-Password",
      "Hostname",
      "ROS-Agent-IP"
    ]
  }

=== chhartmann/RoboProg/data/config.json
{
	"limits": [{
		"min": 0,
		"max": 180
	}, {
		"min": 0,
		"max": 180
	}, {
		"min": 0,
		"max": 180
	}, {
		"min": 0,
		"max": 180
	}],
	"home": [90, 90, 90, 90],
	"Autostart-Script": false,
	"Wifi-SSID": "",
	"Wifi-Password": "",
	"Hostname": "ESP-RobotProg",
	"ROS-Agent-IP": ""
}
